import {useEffect,useRef,useState} from 'react';
import {api,downloadText,filesBase64} from './api';
import {WorldView} from './WorldView';
import {quatToRpy,rpyToQuat,type Vec3,type Quat} from './spatial';
import {POSITION_NED,BODY_VELOCITY,type ReplayState} from './contracts';
import './styles.css';

type Definition={kind:string;id:string;version:string;source:string;payload:Record<string,any>};
type Project={config:any;definitions:Definition[]};
type Frame={master_step:number;sim_time_s:number;states:Record<string,ReplayState>;reward:Record<string,number>;terminated:boolean;termination_reason:string|null;action:any;observation:number[]|null;events:string[];actuator_commands:any};
type Job={run_id:string;state:string;step:number;experiment_hash?:string;reward_total?:number;success?:boolean;collisions?:number;error?:string;failure_category?:string;failure_stage?:string;termination_reason?:string;artifact_path?:string};
type Check={category:string;name:string;status:string;message:string;metrics:Record<string,number>;path:string;code:string};
type Report={status:string;checks:Check[];experiment_hash?:string};
type ComponentType={type:string;display_name:string;parameters:Record<string,unknown>};
const steps=['Vessel','Environment','Scenario','Task','Qualification','Runs','Replay'] as const;
type Step=typeof steps[number];
const deepCopy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
function NumberField({label,value,onChange,step=.1}:{label:string;value:number;onChange:(value:number)=>void;step?:number}){return <label className="field"><span>{label}</span><input type="number" step={step} value={Number.isFinite(value)?value:0} onChange={e=>{const x=Number(e.target.value);if(Number.isFinite(x))onChange(x)}}/></label>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="field"><span>{label}</span><input value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function VecFields({label,value,onChange,axes=['X','Y','Z']}:{label:string;value:number[];onChange:(v:number[])=>void;axes?:string[]}){return <div className="field-group"><b>{label}</b><div className="field-row">{axes.map((axis,i)=><NumberField key={axis} label={axis} value={value?.[i]??0} onChange={x=>{const next=[...value];next[i]=x;onChange(next)}}/>)}</div></div>}
const ref=(d:Definition)=>`${d.id}@${d.version}`;

export default function App(){
 const [project,setProject]=useState<Project|null>(null),[original,setOriginal]=useState<Project|null>(null),[text,setText]=useState('');
 const [step,setStep]=useState<Step>('Vessel'),[tab,setTab]=useState<'Visual'|'Config'|'Diff'>('Visual'),[selected,setSelected]=useState('vessel');
 const [status,setStatus]=useState('Loading preset'),[report,setReport]=useState<Report|null>(null),[diff,setDiff]=useState<any[]>([]);
 const [jobs,setJobs]=useState<Job[]>([]),[runId,setRunId]=useState(localStorage.getItem('manta-run-id')||''),[job,setJob]=useState<Job|null>(null);
 const [frame,setFrame]=useState<Frame|null>(null),[trail,setTrail]=useState<{states:Record<string,{position_display_m:Vec3}>}[]>([]),[seek,setSeek]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1);
 const [metrics,setMetrics]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([]),[policyId,setPolicyId]=useState(''),[policies,setPolicies]=useState<Record<string,any>>({});
 const [artifacts,setArtifacts]=useState<{path:string;size_bytes:number;sha256:string}[]>([]);
 const loadedArtifactsFor=useRef('');
 const stepRef=useRef<Step>(step),seekRef=useRef(seek);
 stepRef.current=step;seekRef.current=seek;
 const [sensorTypes,setSensorTypes]=useState<ComponentType[]>([]),[actuatorTypes,setActuatorTypes]=useState<ComponentType[]>([]);
 const [runMode,setRunMode]=useState<'scripted_waypoint'|'policy_evaluation'>('scripted_waypoint');
 useEffect(()=>{if(!runId)api<Project>('/v1/presets/navigation').then(p=>{setProject(p);setOriginal(deepCopy(p));setText(JSON.stringify(p,null,2));setStatus('Preset loaded')}).catch(e=>setStatus((e as Error).message));refreshJobs();refreshPolicies();api<ComponentType[]>('/v1/component-types/sensors').then(setSensorTypes).catch(()=>{});api<ComponentType[]>('/v1/component-types/actuators').then(setActuatorTypes).catch(()=>{})},[]);
 useEffect(()=>{if(!runId)return;api<Project>(`/v1/jobs/${encodeURIComponent(runId)}/experiment`).then(p=>{setProject(p);setOriginal(deepCopy(p));setText(JSON.stringify(p,null,2));setStatus(`Loaded run ${runId}`)}).catch(()=>{api<Project>('/v1/presets/navigation').then(p=>{setProject(p);setOriginal(deepCopy(p));setText(JSON.stringify(p,null,2))}).catch(()=>{})})},[runId]);
 useEffect(()=>{if(project&&tab!=='Config')setText(JSON.stringify(project,null,2))},[project,tab]);
 useEffect(()=>{if(!runId)return;let live=true;async function poll(){try{const s=await api<Job>(`/v1/jobs/${encodeURIComponent(runId)}`);if(!live)return;setJob(s);if(s.step>=0){const followLive=stepRef.current!=='Replay'||seekRef.current===0||seekRef.current>=s.step-5;if(followLive){const page=await api<{items:Frame[]}>(`/v1/jobs/${encodeURIComponent(runId)}/frames?offset=${s.step}&limit=1`);if(page.items[0]){setFrame(page.items[0]);setSeek(s.step)}}}const m=await api<{items:any[]}>(`/v1/jobs/${encodeURIComponent(runId)}/metrics?offset=${Math.max(0,s.step-200)}&limit=200`);if(live)setMetrics(m.items);const l=await api<{items:any[]}>(`/v1/jobs/${encodeURIComponent(runId)}/logs?offset=0&limit=100`);if(live)setLogs(l.items);if((s.state==='COMPLETED'||s.state==='STOPPED')&&loadedArtifactsFor.current!==runId){loadedArtifactsFor.current=runId;loadTrail(runId,s.step);const a=await api<{artifacts:typeof artifacts}>(`/v1/jobs/${encodeURIComponent(runId)}/artifacts`);if(live)setArtifacts(a.artifacts)}}catch(e){if(live)setStatus((e as Error).message)}}poll();const timer=setInterval(poll,1200);return()=>{live=false;clearInterval(timer)}},[runId]);
 useEffect(()=>{if(!playing||!job)return;const timer=setInterval(()=>setSeek(x=>Math.min(job.step,x+1)),Math.max(40,150/speed));return()=>clearInterval(timer)},[playing,job?.step,speed]);
 useEffect(()=>{if(!runId||!job)return;let active=true;api<{items:Frame[]}>(`/v1/jobs/${encodeURIComponent(runId)}/frames?offset=${seek}&limit=1`).then(p=>{if(active&&p.items[0])setFrame(p.items[0])}).catch(()=>{});return()=>{active=false}},[seek,runId]);
 function mutate(fn:(p:Project)=>void){setProject(old=>{if(!old)return old;const next=deepCopy(old);fn(next);setReport(null);return next})}
 const defs=project?.definitions||[],vessel=project?.config.vessels?.[0],vesselDef=defs.find(d=>d.kind==='vessel'&&ref(d)===vessel?.definition);
 const taskDef=defs.find(d=>d.kind==='task'&&ref(d)===project?.config.task?.type);
 const findDef=(kind:string,id:string)=>defs.find(d=>d.kind===kind&&d.id===id);
 const editDef=(kind:string,id:string,fn:(p:any)=>void)=>mutate(p=>{const d=p.definitions.find(d=>d.kind===kind&&d.id===id);if(d)fn(d.payload)});
 const editConfig=(fn:(c:any)=>void)=>mutate(p=>fn(p.config));
 function componentFields(kind:'sensor'|'actuator',id:string,payload:any){
  const description=(kind==='sensor'?sensorTypes:actuatorTypes).find(x=>x.type===payload.kind);
  if(!description)return <p className="muted">Component metadata unavailable. Edit this definition in Config.</p>;
  return Object.keys(description.parameters).filter(key=>payload[key]!==undefined||key==='mount_frd_m'||key==='mount_q_to_frd').map(key=>{
   const value=payload[key]??(key==='mount_frd_m'?[0,0,0]:key==='mount_q_to_frd'?[1,0,0,0]:undefined);
   if(key==='mount_q_to_frd'){const euler=quatToRpy(value as Quat).map(x=>x*180/Math.PI);return <VecFields key={key} label="Orientation (deg)" value={euler} axes={['Roll','Pitch','Yaw']} onChange={v=>editDef(kind,id,p=>p[key]=rpyToQuat(v.map(x=>x*Math.PI/180) as Vec3))}/>}
   if(Array.isArray(value))return <VecFields key={key} label={key} value={value} axes={key==='mount_frd_m'?['Forward','Right','Down']:value.map((_:unknown,i:number)=>String(i+1))} onChange={v=>editDef(kind,id,p=>p[key]=v)}/>;
   if(typeof value==='number')return <NumberField key={key} label={key} value={value} onChange={v=>editDef(kind,id,p=>p[key]=v)}/>;
   return null;
  });
 }
 async function refreshJobs(){try{setJobs(await api<Job[]>('/v1/jobs'))}catch{}}
 async function refreshPolicies(){try{setPolicies(await api<Record<string,any>>('/v1/policies'))}catch{}}
 async function importFile(file:File|null){if(!file)return;try{const format=/\.ya?ml$/i.test(file.name)?'yaml':'json';const raw=await api<Project>('/v1/experiments/parse',{method:'POST',body:JSON.stringify({content:await file.text(),format})});setProject(raw);setOriginal(deepCopy(raw));setText(JSON.stringify(raw,null,2));setReport(null);setStatus(`Imported ${file.name}`)}catch(e){setStatus((e as Error).message)}}
 function currentConfigKind(){return ({Vessel:'vessel',Environment:'environment',Scenario:'scenario',Task:'task'} as Record<string,string>)[step]}
 function currentPayload():any{if(step==='Vessel')return vesselDef?.payload;if(step==='Environment')return project?.config.world.environment;if(step==='Scenario')return project?.config;if(step==='Task')return taskDef?.payload;return null}
 async function importComponent(file:File|null){const kind=currentConfigKind();if(!file||!kind)return;try{const format=/\.ya?ml$/i.test(file.name)?'yaml':'json',content=await file.text();if(kind==='vessel'){try{const assembly=await api<{vessel:any;definitions:Definition[]}>('/v1/vessel-assembly/parse',{method:'POST',body:JSON.stringify({content,format})});mutate(p=>{const old=p.config.vessels[0].instance_id;p.config.vessels[0]=assembly.vessel;p.definitions=[...p.definitions.filter(d=>!['vessel','actuator','sensor'].includes(d.kind)),...assembly.definitions];const task=p.definitions.find(d=>d.kind==='task'&&d.payload.agent_id===old);if(task)task.payload.agent_id=assembly.vessel.instance_id});setStatus(`Imported vessel assembly from ${file.name}`);return}catch{}}
   const document=await api<{payload:any}>(`/v1/configs/${kind}/import`,{method:'POST',body:JSON.stringify({content,format})});mutate(p=>{if(kind==='vessel'){const d=p.definitions.find(d=>d.kind==='vessel'&&ref(d)===p.config.vessels[0].definition);if(d)d.payload=document.payload}else if(kind==='environment')p.config.world.environment=document.payload;else if(kind==='scenario')p.config=document.payload;else{const d=p.definitions.find(d=>d.kind==='task'&&ref(d)===p.config.task.type);if(d)d.payload=document.payload}});setStatus(`Imported ${kind} from ${file.name}`)}catch(e){setStatus((e as Error).message)}}
 async function exportComponent(format:'json'|'yaml'){const kind=currentConfigKind(),payload=currentPayload();if(!kind||!payload||!project)return;try{let response:{content:string};if(kind==='vessel'){const refs=new Set([vessel.definition,...(vessel.actuators||[]),...(vessel.sensors||[])]);const assembly={schema_version:1,vessel,definitions:project.definitions.filter(d=>['vessel','actuator','sensor'].includes(d.kind)&&refs.has(ref(d)))};response=await api<{content:string}>('/v1/vessel-assembly/serialize',{method:'POST',body:JSON.stringify({document:assembly,format})})}else response=await api<{content:string}>(`/v1/configs/${kind}/export`,{method:'POST',body:JSON.stringify({document:{schema_version:1,payload},format})});downloadText(`manta-${kind}.${format}`,response.content,format==='yaml'?'application/yaml':'application/json');setStatus(`Exported ${kind}`)}catch(e){setStatus((e as Error).message)}}
 async function exportFile(format:'json'|'yaml'){if(!project)return;try{const response=await api<{content:string}>('/v1/experiments/serialize',{method:'POST',body:JSON.stringify({...project,format})});downloadText(`manta-experiment.${format==='yaml'?'yaml':'json'}`,response.content,format==='yaml'?'application/yaml':'application/json');setStatus(`Exported ${format.toUpperCase()}`)}catch(e){setStatus((e as Error).message)}}
 async function applyText(){try{const raw=JSON.parse(text) as Project;if(!raw.config||!Array.isArray(raw.definitions))throw new Error('Expected config and definitions');await api('/v1/validate',{method:'POST',body:JSON.stringify(raw)});setProject(raw);setStatus('Config applied')}catch(e){setStatus((e as Error).message)}}
 async function validate(){if(!project)return;try{const result=await api<{config_hash:string}>('/v1/validate',{method:'POST',body:JSON.stringify(project)});setStatus(`Resolved · ${result.config_hash.slice(0,12)}`)}catch(e){setStatus((e as Error).message)}}
 async function qualify(){if(!project)return;try{setStatus('Qualifying with the simulator…');const result=await api<Report>('/v1/qualify',{method:'POST',body:JSON.stringify(project)});setReport(result);setTab('Visual');setStep('Qualification');setStatus(`Qualification ${result.status}`)}catch(e){setStatus((e as Error).message)}}
 async function showDiff(){if(!project||!original)return;try{const result=await api<{changes:any[]}>('/v1/configs/scenario/diff',{method:'POST',body:JSON.stringify({left:{schema_version:1,payload:original.config},right:{schema_version:1,payload:project.config}})});const changedDefs=project.definitions.filter(d=>JSON.stringify(d)!==JSON.stringify(original.definitions.find(o=>o.kind===d.kind&&o.id===d.id)));setDiff([...result.changes,...changedDefs.map(d=>({path:`/definitions/${d.kind}/${d.id}`,after:d.payload}))]);setTab('Diff')}catch(e){setStatus((e as Error).message)}}
 async function start(){if(!project)return;try{setStatus('Submitting to local runner…');const id=`web-${Date.now()}`;const result=await api<Job>('/v1/jobs',{method:'POST',body:JSON.stringify({...project,run_id:id,mode:runMode,policy_id:runMode==='policy_evaluation'?policyId:null,step_delay_s:.02})});setRunId(id);localStorage.setItem('manta-run-id',id);setJob(result);setTab('Visual');setStep('Runs');setStatus(`Run ${id} queued`);refreshJobs()}catch(e){setStatus((e as Error).message)}}
 async function upload(files:FileList|null){if(!files)return;try{const encoded=await filesBase64(files);const manifest=JSON.parse(atob(encoded['manifest.json']));await api('/v1/policies',{method:'POST',body:JSON.stringify({policy_id:manifest.policy_id,files_base64:encoded,observation_contract_hash:manifest.observation_contract_hash,action_contract_hash:manifest.action_contract_hash})});setPolicyId(manifest.policy_id);setStatus(`Policy ${manifest.policy_id} validated`);refreshPolicies()}catch(e){setStatus((e as Error).message)}}
 async function control(action:'stop'|'kill'){if(!runId)return;try{await api(`/v1/jobs/${encodeURIComponent(runId)}/${action}`,{method:'POST'});setStatus(`${action} requested`)}catch(e){setStatus((e as Error).message)}}
 async function loadTrail(id:string,_end:number){const result=await api<{frames:{states:Record<string,{position_display_m:Vec3}>}[]}>(`/v1/jobs/${encodeURIComponent(id)}/trajectory?max_points=1000`);setTrail(result.frames)}
 function selectJob(id:string){loadedArtifactsFor.current='';setRunId(id);localStorage.setItem('manta-run-id',id);setTrail([]);setArtifacts([]);setSeek(0);setStep('Replay')}
 function inspector(){if(!project||!vessel)return null;
  if(step==='Vessel'){
   if(selected.startsWith('sensor:')){const id=selected.slice(7),d=findDef('sensor',id);if(!d)return null;return <><h3>{id} · {d.payload.kind}</h3>{componentFields('sensor',id,d.payload)}</>}
   if(selected.startsWith('actuator:')){const id=selected.slice(9),d=findDef('actuator',id);if(!d)return null;return <><h3>{id} · {d.payload.kind}</h3>{componentFields('actuator',id,d.payload)}</>}
   return <><h3>Vessel</h3><TextField label="Instance name" value={vessel.instance_id} onChange={v=>mutate(p=>{const old=p.config.vessels[0].instance_id;p.config.vessels[0].instance_id=v;const task=p.definitions.find(d=>d.kind==='task'&&d.payload.agent_id===old);if(task)task.payload.agent_id=v})}/><NumberField label="Mass (kg)" value={vesselDef?.payload.mass_kg||0} onChange={v=>editDef('vessel',vesselDef!.id,p=>p.mass_kg=v)}/><VecFields label="Hull half extents (m)" value={vesselDef?.payload.collision?.half_extents_m||[1,.5,.3]} axes={['Forward','Right','Down']} onChange={v=>editDef('vessel',vesselDef!.id,p=>p.collision.half_extents_m=v)}/><p className="muted">Select a sensor or actuator in the list or scene for exact positioning.</p></>}
  if(step==='Environment'){const env=project.config.world.environment;return <><h3>Environment</h3><NumberField label="Seabed depth NED (m)" value={project.config.world.bathymetry?.bottom_ned_z_m||0} onChange={v=>editConfig(c=>c.world.bathymetry.bottom_ned_z_m=v)}/><VecFields label="Current NED (m/s)" value={env.current.ned_mps} axes={['North','East','Down']} onChange={v=>editConfig(c=>c.world.environment.current.ned_mps=v)}/><VecFields label="Wind NED (m/s)" value={env.wind.ned_mps} axes={['North','East','Down']} onChange={v=>editConfig(c=>c.world.environment.wind.ned_mps=v)}/>{(project.config.world.static_entities||[]).map((x:any)=><VecFields key={x.id} label={`Obstacle ${x.id} NED (m)`} value={x[POSITION_NED]} axes={['North','East','Down']} onChange={v=>editConfig(c=>c.world.static_entities.find((a:any)=>a.id===x.id)[POSITION_NED]=v)}/>)}</>}
  if(step==='Scenario'){return <><h3>Scenario</h3><VecFields label="Spawn NED (m)" value={vessel.spawn.ned_m} axes={['North','East','Down']} onChange={v=>editConfig(c=>c.vessels[0].spawn.ned_m=v)}/><NumberField label="Spawn yaw (deg)" value={vessel.spawn.rpy_rad[2]*180/Math.PI} onChange={v=>editConfig(c=>c.vessels[0].spawn.rpy_rad[2]=v*Math.PI/180)}/><VecFields label="Goal NED (m)" value={taskDef?.payload.target_ned_m||[0,0,0]} axes={['North','East','Down']} onChange={v=>taskDef&&editDef('task',taskDef.id,p=>p.target_ned_m=v)}/><NumberField label="Goal radius (m)" value={taskDef?.payload.radius_m||1} onChange={v=>taskDef&&editDef('task',taskDef.id,p=>p.radius_m=v)}/><NumberField label="Maximum steps" value={project.config.simulation.max_master_steps} step={1} onChange={v=>editConfig(c=>c.simulation.max_master_steps=Math.round(v))}/><p className="muted">Click the world plane to move the goal.</p></>}
  if(step==='Task')return <><h3>{['waypoint','waypoint_team','formation','coverage'].includes(taskDef?.payload.kind)?'Navigation task':'Custom Python component'}</h3><p>Primitive: {taskDef?.payload.kind||'unknown'}</p><p>Observation sources: GPS, IMU, sonar</p><p>Action interface: {vessel.controller.mode}</p><p>Reward weights: {JSON.stringify(project.config.task.reward)}</p><p>Termination: goal radius or maximum steps</p>{!['waypoint','waypoint_team','formation','coverage'].includes(taskDef?.payload.kind)&&<pre>{JSON.stringify(taskDef?.payload,null,2)}</pre>}</>;
  if(step==='Replay'&&frame)return <><h3>Step {frame.master_step}</h3><p>Time {frame.sim_time_s.toFixed(2)} s</p><pre>{JSON.stringify({action:frame.action,observation:frame.observation,reward:frame.reward,velocity:frame.states?.[vessel.instance_id]?.[BODY_VELOCITY],events:frame.events},null,2)}</pre></>;
  return <><h3>Run status</h3><p>{job?.state||'No run selected'}</p><p>{job?.error}</p></>;
 }
 if(!project)return <main><header><h1>MANTA</h1><p>{status}</p></header></main>;
 return <main><header><div><span className="eyebrow">MANTA CONTROL PLANE</span><h1>Build · Qualify · Evaluate</h1></div><div className="status"><i/> {status}</div></header>
 <div className="shell"><nav>{steps.map((name,i)=><button key={name} className={name===step?'active':''} onClick={()=>{setStep(name);setTab('Visual')}}><span>0{i+1}</span>{name}</button>)}</nav>
 <section className="work"><div className="title"><div><p>CANONICAL EXPERIMENT</p><h2>{step}</h2></div><div className="actions"><label className="button-like">Import experiment<input type="file" accept=".json,.yaml,.yml,application/json" hidden onChange={e=>importFile(e.target.files?.[0]||null)}/></label>{currentConfigKind()&&<label className="button-like">Import {currentConfigKind()}<input type="file" accept=".json,.yaml,.yml,application/json" hidden onChange={e=>importComponent(e.target.files?.[0]||null)}/></label>}<button onClick={()=>exportFile('json')}>Export JSON</button><button onClick={()=>exportFile('yaml')}>Export YAML</button>{currentConfigKind()&&<button onClick={()=>exportComponent('yaml')}>Export {currentConfigKind()}</button>}<button onClick={validate}>Validate</button><button onClick={qualify}>Qualify</button><button className="primary" onClick={start}>Run backend</button></div></div>
 {(step==='Vessel'||step==='Environment'||step==='Scenario'||step==='Task'||step==='Replay')&&<div className="tabbar">{(['Visual','Config','Diff'] as const).map(t=><button className={tab===t?'active':''} key={t} onClick={()=>t==='Diff'?showDiff():setTab(t)}>{t}</button>)}</div>}
 {tab==='Config'?<div className="config-panel"><textarea value={text} onChange={e=>setText(e.target.value)} spellCheck={false}/><button onClick={applyText}>Apply config</button></div>:tab==='Diff'?<div className="diff-panel"><h3>Changes since import</h3><pre>{JSON.stringify(diff,null,2)}</pre></div>:<>
 {(step==='Vessel'||step==='Environment'||step==='Scenario'||step==='Task'||step==='Replay')&&<div className="workspace"><aside className="object-list"><h3>Objects</h3>{step==='Vessel'?<><button onClick={()=>setSelected('vessel')}>Hull · {vessel?.instance_id}</button>{defs.filter(d=>d.kind==='actuator').map(d=><button key={d.id} onClick={()=>setSelected(`actuator:${d.id}`)}>Actuator · {d.id}</button>)}{defs.filter(d=>d.kind==='sensor').map(d=><button key={d.id} onClick={()=>setSelected(`sensor:${d.id}`)}>Sensor · {d.id}</button>)}</>:<><button onClick={()=>setSelected('goal')}>Goal</button><button onClick={()=>setSelected('vessel')}>Vessel</button>{(project.config.world.static_entities||[]).map((e:any)=><button key={e.id} onClick={()=>setSelected(`obstacle:${e.id}`)}>Obstacle · {e.id}</button>)}</>}</aside><WorldView project={project} frame={step==='Replay'?frame:null} trail={step==='Replay'?trail:[]} selected={selected} onSelect={setSelected} onMoveGoal={step==='Scenario'?v=>taskDef&&editDef('task',taskDef.id,p=>p.target_ned_m=v):undefined}/><aside className="inspector">{inspector()}</aside></div>}
 {step==='Qualification'&&<div className="qualifications">{report?<><h3>Experiment {report.experiment_hash?.slice(0,12)} · {report.status}</h3>{report.checks.map((c,i)=><article key={i}><span className={`badge ${c.status.toLowerCase()}`}>{c.status}</span><div><b>{c.category.toUpperCase()} · {c.name}</b><p>{c.message||c.code||JSON.stringify(c.metrics)}</p></div></article>)}</>:<p>Run qualification to check schema, physical parameters, sensor contracts, reset, control response, and determinism.</p>}</div>}
 {step==='Runs'&&<div className="run-panel"><div className="run-setup"><h3>Local runner</h3><label>Mode <select value={runMode} onChange={e=>setRunMode(e.target.value as typeof runMode)}><option value="scripted_waypoint">Scripted navigation baseline</option><option value="policy_evaluation">Evaluate uploaded policy</option></select></label>{runMode==='policy_evaluation'&&<><label>Policy <select value={policyId} onChange={e=>setPolicyId(e.target.value)}><option value="">Select a bundle</option>{Object.keys(policies).map(id=><option key={id} value={id}>{id}</option>)}</select></label><label>Upload seven policy bundle files <input type="file" multiple onChange={e=>upload(e.target.files)}/></label></>}<p>One vessel · waypoint · up to 10,000 simulator steps</p><button className="primary" onClick={start}>Start run</button></div><div><h3>Runs</h3><button onClick={refreshJobs}>Refresh</button>{jobs.map(j=><button className="job-row" key={j.run_id} onClick={()=>selectJob(j.run_id)}>{j.run_id} · {j.state} · step {j.step}</button>)}{job?.error&&<p className="run-error"><b>{job.failure_category||'RUN ERROR'} · {job.failure_stage||'runner'}</b><br/>{job.error}</p>}{job&&<div className="cards"><article><label>Status</label><strong>{job.state}</strong></article><article><label>Step</label><strong>{job.step}</strong></article><article><label>Reward</label><strong>{job.reward_total?.toFixed(2)||'—'}</strong></article><article><label>Success</label><strong>{job.success?'yes':'no'}</strong></article></div>}<div className="actions"><button disabled={!job||!['QUEUED','RUNNING'].includes(job.state)} onClick={()=>control('stop')}>Stop gracefully</button><button disabled={!job||!['QUEUED','RUNNING'].includes(job.state)} onClick={()=>control('kill')}>Kill</button></div><h3>Live metrics</h3><pre>{JSON.stringify(metrics.slice(-5),null,2)}</pre><h3>Logs</h3><pre>{logs.map(l=>l.message).join('\n')}</pre>{artifacts.length>0&&<><h3>Artifacts</h3>{artifacts.map(a=><a className="artifact-link" key={a.path} href={`/v1/artifacts/${encodeURIComponent(runId)}/${a.path.split('/').map(encodeURIComponent).join('/')}`} target="_blank" rel="noreferrer">{a.path} · {(a.size_bytes/1024).toFixed(1)} KiB</a>)}</>}</div></div>}
 {step==='Replay'&&job&&<div className="timeline"><button onClick={()=>setPlaying(!playing)}>{playing?'Pause':'Play'}</button><input type="range" min="0" max={job.step} value={Math.min(seek,job.step)} onChange={e=>setSeek(Number(e.target.value))}/><span>Step {seek} / {job.step}</span><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></div>}
 </>}
 </section></div><footer>Backend-authoritative simulation · NED / FRD / SI · Persistent local jobs</footer></main>;
}
