const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Module=require('node:module');
const ts=require('typescript');
const sourcePath=path.resolve(__dirname,'../src/spatial.ts');
const source=fs.readFileSync(sourcePath,'utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const loaded=new Module(sourcePath,module);loaded.filename=sourcePath;loaded.paths=Module._nodeModulePaths(path.dirname(sourcePath));loaded._compile(code,sourcePath);
const s=loaded.exports;
const close=(actual,expected,tol=1e-9)=>actual.forEach((x,i)=>assert.ok(Math.abs(x-expected[i])<tol,`${actual} != ${expected}`));
close(s.nedToWeb([1,2,3]),[2,-3,1]);
close(s.webToNed([2,-3,1]),[1,2,3]);
close(s.frdToLocal([1,2,3]),[2,-3,1]);
close(s.nedToWeb(s.rotate(s.rpyToQuat([0,0,0]),[1,0,0])),[0,0,1]);
close(s.nedToWeb(s.rotate(s.rpyToQuat([0,0,Math.PI/2]),[1,0,0])),[1,0,0]);
close(s.nedToWeb(s.rotate(s.rpyToQuat([0,0,0]),[0,1,0])),[1,0,0]);
close(s.nedToWeb(s.rotate(s.rpyToQuat([0,0,0]),[0,0,1])),[0,-1,0]);
const q=s.rpyToQuat([0.1,-0.2,0.3]);close(s.quatToRpy(q),[0.1,-0.2,0.3]);
const body=s.bodyQuaternion(s.rpyToQuat([0,0,Math.PI/2]));
close(new (require('three').Vector3)(0,0,1).applyQuaternion(body).toArray(),[1,0,0]);
close(s.mountedDirection(s.rpyToQuat([0,-Math.PI/6,Math.PI/6]),[0,0,1]),s.frdToLocal(s.rotate(s.rpyToQuat([0,-Math.PI/6,Math.PI/6]),[0,0,1])));
console.log('Spatial contract: 10 checks passed');
